spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wanted
    username: wanted
    password: be31
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true